org.gradle.jvmargs=-Xmx2G

# Mod Properties
mod_id=rcguard
mod_name=RCGuard
mod_version=1.0
accepted_minecraft_versions=[1.8.9]

# your package name; see http://maven.apache.org/guides/mini/guide-naming-conventions.html
mod_group=me.shvaich

# this will be the name of the .jar, it can be whatever you like
mod_base_name=RCGuard